Fix long term storage (#3)
* Initial commit

* Fix checkout and obs copying

* Adding debug, fixing missing chars

* adding prometheus for debugging purposes

* Fixes in paths

* Typo

* typo

* Fix type

* Cleanup

* Removing debugging port

* Fixing missing adjustment for Grafana

* Bumping checkout version

* Adding Grafana scrape interval

* Bumping to latest release and adding new feats from deploy-prometheus

* Testing with latest release

* Fixing path

* Fixing ansible run

* Bump to latest commons version

* Small final tweaks

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -33,7 +33,7 @@ inputs:
   # EC2 Instance config
   aws_ec2_instance_type:
     description: 'The AWS EC2 instance type'
-    default: t2.medium
+    default: t3.medium
     required: false
   aws_ec2_instance_profile:
     description: 'The AWS IAM instance profile to use for the EC2 instance. Use if you want to pass an AWS role with specific permissions granted to the instance'
@@ -53,10 +53,6 @@ inputs:
     description: 'AMI filter to use when searching for an AMI to use for the EC2 instance. Defaults to `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*`'
     default: 'ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*'
     required: false
-  infrastructure_only:
-    description: 'Set to true to provision infrastructure (with Terraform) but skip the app deployment (with ansible)'
-    default: "false"
-    required: false
   env_ghs:
     description: 'Set to true to include a Github Secrets (.env formatted) in the environment variables'
     default: ""
@@ -70,6 +66,32 @@ inputs:
   prometheus_config:
     description: 'Path to the prometheus config file'
     default: observability/prometheus/prometheus.yml
+    required: false
+  grafana_scrape_interval:
+    description: 'How frequently to scrape targets by default in the Prometheus data-source.'
+    required: false
+  prometheus_scrape_interval:
+    description: 'How frequently to scrape targets by default'
+    default: 15s
+    required: false
+  prometheus_retention_period:
+    description: 'When to remove old data. Defaults to 15d.'
+    default: 15d
+    required: false
+  cadvisor_enable:
+    description: 'Enable cadvisor container in docker-compose'
+    required: false
+  cadvisor_extra_targets:
+    description: 'Add cadvisor target'
+    required: false
+  node_exporter_enable:
+    description: 'Enable node-exporter container in docker-compose'
+    required: false
+  node_exporter_extra_targets:
+    description: 'Add node-exporter target'
+    required: false
+  print_yaml_files:
+    descritpion: 'Prints docker-compose, prometheus and grafana yaml files. For debugging purposes.'
     required: false
 
   # Stack Management
@@ -137,22 +159,67 @@ inputs:
   aws_vpc_subnet_id:
     description: 'Specify a Subnet to be used with the instance. If none provided, will pick one.'
     required: false
+  aws_vpc_enable_nat_gateway:
+    description: 'Enables NAT gateway'
+    required: false
+  aws_vpc_single_nat_gateway:
+    description: 'Creates only one NAT gateway'
+    required: false
+  aws_vpc_external_nat_ip_ids:
+    description: 'Comma separated list of IP IDS to reuse in the NAT gateways'
+    required: false
   aws_vpc_additional_tags:
     description: 'A JSON object of additional tags that will be included on created resources. Example: `{"key1": "value1", "key2": "value2"}`'
     required: false
 
+  # Advanced Options
+  docker_cloudwatch_enable:
+    description: 'Toggle cloudwatch creation for Docker containers.'
+    required: false
+    default: true
+  docker_cloudwatch_skip_destroy:
+    description: 'Toggle deletion or not when destroying the stack.'
+    required: false
+    default: false
+  aws_ec2_instance_public_ip:
+    description: 'Add a public IP to the instance or not. (Not an Elastic IP)'
+    required: false
+    default: true
+  aws_ec2_port_list:
+    description: 'List of ports to be enabled as an ingress rule in the EC2 SG, in a [xx,yy] format - Not the ELB'
+    required: false
+  aws_elb_app_port:
+    description: 'Port to expose for the app'
+    required: false
+    default: "8000,3000"
+  aws_elb_listen_port:
+    description: 'Load balancer listening port. Defaults to 80 if NO FQDN provided, 443 if FQDN provided'
+    required: false
+    default: "443,3000"
+
+
 outputs:
+  # VPC
+  aws_vpc_id:
+    description: 'The selected VPC ID used.'
+    value: ${{ steps.deploy.outputs.aws_vpc_id }}
+  # EC2
   vm_url:
     description: 'The URL of the generated app'
     value: ${{ steps.deploy.outputs.vm_url }}
-#        CREATE_VPC: ${{ inputs.aws_create_vpc }}
+  instance_endpoint:
+    description: 'The URL of the generated ec2 instance'
+    value: ${{ steps.deploy.outputs.instance_endpoint }}
+  ec2_sg_id:
+    description: 'SG ID for the EC2 instance'
+    value: ${{ steps.deploy.outputs.ec2_sg_id }}
 
 runs:
   using: 'composite'
   steps:
     - name: Checkout
       if: ${{ inputs.checkout == 'true' }}
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
 
     - name: Invert boolean Variable
       shell: bash
@@ -162,52 +229,127 @@ runs:
 
     # take the grafana datasource and prometheus config and put them in the right place (root of the deployment repo)
     - name: Copy Observability Data
-      if: ${{ inputs.infrastructure_only == 'false' }}
       shell: bash
       env:
         GITHUB_ACTION_PATH: ${{ github.action_path }}
       run: |
         echo "Copying Observability Data"
-
+        
+        # Copy Grafana Datasource
         echo "    Grafana Datasource - from ${{ inputs.grafana_datasource_dir }} to $GITHUB_ACTION_PATH/observability/grafana/datasources"
-        mkdir -p $GITHUB_ACTION_PATH/observability/grafana/datasources
-        cp $GITHUB_WORKSPACE/${{ inputs.grafana_datasource_dir }}/* "${GITHUB_ACTION_PATH}/observability/grafana/datasources"
-
+        if [ -d "$GITHUB_WORKSPACE/${{ inputs.grafana_datasource_dir }}" ]; then
+            mkdir -p "$GITHUB_ACTION_PATH/observability/grafana"
+            cp -r "$GITHUB_WORKSPACE/${{ inputs.grafana_datasource_dir }}" "${GITHUB_ACTION_PATH}/observability/grafana"
+        else
+            echo "    Directory ${{ inputs.grafana_datasource_dir }} not found. Using default instead."
+        fi
+        # Copy Prometheus Config
         echo "    Prometheus Config - from ${{ inputs.prometheus_config }} to $GITHUB_ACTION_PATH/observability/prometheus"
-        mkdir -p $GITHUB_ACTION_PATH/observability/prometheus
-        cp $GITHUB_WORKSPACE/${{ inputs.prometheus_config }} "${GITHUB_ACTION_PATH}/observability/prometheus"
+        if [ -e "$GITHUB_WORKSPACE/${{ inputs.prometheus_config }}" ]; then
+            mkdir -p "$GITHUB_ACTION_PATH/observability/prometheus"
+            cp "$GITHUB_WORKSPACE/${{ inputs.prometheus_config }}" "${GITHUB_ACTION_PATH}/observability/prometheus"
+        else
+            echo "    File ${{ inputs.prometheus_config }} not found. Using default instead."
+        fi
 
-    # copy the whole deployment repo (in the github action path) to the deployment repo (in the github workspace)
-    - name: Copy Deployment Repo
-      if: ${{ inputs.infrastructure_only == 'false' }}
+
+
+    - name: Setting up Grafana options
+      if: ${{ inputs.grafana_scrape_interval != '' }}
+      shell: bash
+      run: |
+        # Adding grafana timeInterval if set
+        yq eval -i '.datasources[] |= select(.type == "prometheus" and .isDefault == true) |= . + {"timeInterval": "${{ inputs.grafana_scrape_interval }}"}'  "${{ github.action_path }}/observability/grafana/datasources/sources.yml"
+
+    - name: Setting up Prometheus options
+      shell: bash
+      run: |    
+        # Adding prometheus global defaults
+        yq eval -i '.global.scrape_interval = "${{ inputs.prometheus_scrape_interval }}"'  "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+        yq eval -i '.global.evaluation_interval = "${{ inputs.prometheus_scrape_interval }}"'  "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+        yq eval -i '.services.prometheus.command += ["--storage.tsdb.retention.time=${{ inputs.prometheus_retention_period }}"]' "${{ github.action_path }}/docker-compose.yaml"
+
+    - name: Enable cadvisor
+      if: ${{ inputs.cadvisor_enable == 'true' }}
+      shell: bash
+      run: |
+        yq eval -i 'select(fileIndex == 0) * {"services": {"cadvisor": {"image": "gcr.io/cadvisor/cadvisor", "container_name": "cadvisor", "volumes": ["/:/rootfs:ro", "/var/run:/var/run:ro", "/sys:/sys:ro", "/var/lib/docker/:/var/lib/docker:ro","/dev/disk/:/dev/disk:ro" ], "ports": ["8080:8080"], "restart": "unless-stopped"}}}' "${{ github.action_path }}/docker-compose.yaml"
+        yq eval -i '.scrape_configs += [{"job_name": "cadvisor", "honor_timestamps": true, "metrics_path": "/metrics", "scheme": "http", "follow_redirects": true, "enable_http2": true, "static_configs": [{"targets": ["cadvisor:8080"]}]}]' "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+
+    - name: Add cadvisor targets to prometheus
+      if: ${{ inputs.cadvisor_extra_targets != '' }}
+      shell: bash
+      run: |
+        if ! grep -q "job_name: cadvisor" "${{ github.action_path }}/observability/prometheus/prometheus.yml"; then
+          yq eval -i '.scrape_configs += [{"job_name": "cadvisor", "honor_timestamps": true, "metrics_path": "/metrics", "scheme": "http", "follow_redirects": true, "enable_http2": true, "static_configs": [{"targets": []}]}]' "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+        fi
+        IFS=',' read -ra target_array <<< "${{ inputs.cadvisor_extra_targets }}"
+        for target in "${target_array[@]}"; do
+          if ! grep -q "$target" "${{ github.action_path }}/observability/prometheus/prometheus.yml"; then
+            yq eval -i 'select(.scrape_configs[].job_name == "cadvisor") | .scrape_configs[] |= (select(.job_name == "cadvisor") | .static_configs[0].targets += ["'$target'"])' "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+          fi
+        done
+
+    - name: Enable node-exporter
+      if: ${{ inputs.node_exporter_enable == 'true' }}
+      shell: bash
+      run: |
+        yq eval -i 'select(fileIndex == 0) * {"services": {"node-exporter": {"image": "quay.io/prometheus/node-exporter:latest", "container_name": "node-exporter", "volumes": ["/proc:/host/proc:ro", "/sys:/host/sys:ro", "/:/rootfs:ro", "/:/host:ro,rslave" ], "command": ["'--path.rootfs=/host'","'--path.procfs=/host/proc'","'--path.sysfs=/host/sys'","--collector.filesystem.ignored-mount-points", "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"], "ports": ["9100:9100"], "restart": "unless-stopped"}}}' "${{ github.action_path }}/docker-compose.yaml"
+        yq eval -i '.scrape_configs += [{"job_name": "node-exporter", "honor_timestamps": true, "metrics_path": "/metrics", "scheme": "http", "static_configs": [{"targets": ["node-exporter:9100"]}]}]' "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+
+    - name: Add node-exporter targets to prometheus
+      if: ${{ inputs.node_exporter_extra_targets != '' }}
+      shell: bash
+      run: |
+        if ! grep -q "job_name: node-exporter" "${{ github.action_path }}/observability/prometheus/prometheus.yml"; then
+          yq eval -i '.scrape_configs += [{"job_name": "node-exporter", "honor_timestamps": true, "metrics_path": "/metrics", "scheme": "http", "static_configs": [{"targets": []}]}]' "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+        fi
+        IFS=',' read -ra target_array <<< "${{ inputs.node_exporter_extra_targets }}"
+        for target in "${target_array[@]}"; do
+          if ! grep -q "$target" "${{ github.action_path }}/observability/prometheus/prometheus.yml"; then
+            yq eval -i 'select(.scrape_configs[].job_name == "node-exporter") | .scrape_configs[] |= (select(.job_name == "node-exporter") | .static_configs[0].targets += ["'$target'"])' "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+          fi
+        done
+
+    - name: Printing resulting yaml files
+      if: ${{ inputs.print_yaml_files == 'true' }}
+      shell: bash
+      run: |
+        echo "docker-compose yaml"
+        cat "${{ github.action_path }}/docker-compose.yaml"
+        echo "Prometheus yaml"
+        cat "${{ github.action_path }}/observability/prometheus/prometheus.yml"
+        echo "Grafana sources yaml"
+        cat "${{ github.action_path }}/observability/grafana/datasources/sources.yml"
+
+    # copy the deployment from the github action path to the github workspace
+    - name: Copy Deployment Config
       shell: bash
       env:
         GITHUB_ACTION_PATH: ${{ github.action_path }}
+        APP_SUBDIR: pixel-tracker-app
       run: |
-
-        echo "Debugging - ls -la $GITHUB_ACTION_PATH/operations/deployment"
-        ls -al $GITHUB_ACTION_PATH
+        app_path=$GITHUB_WORKSPACE/$APP_SUBDIR
 
         echo "Copying app Repo"
-        mkdir -p $GITHUB_WORKSPACE/pixel-tracker-app
-        cp -r $GITHUB_ACTION_PATH/. $GITHUB_WORKSPACE/pixel-tracker-app
+        mkdir -p "$app_path"
+        cp -r  $GITHUB_ACTION_PATH/. "$app_path"
 
         echo "removing operations dir"
-        rm -rf $GITHUB_WORKSPACE/pixel-tracker-app/operations
+        rm -rf $app_path/operations
 
-        echo "Debugging - ls -la $GITHUB_WORKSPACE/pixel-tracker-app"
-        ls -la $GITHUB_WORKSPACE/pixel-tracker-app
-
+        echo "Debugging - ls -la $app_path"
+        ls -la $app_path
 
     - name: Deploy with BitOps
       id: deploy
-      uses: bitovi/github-actions-commons@v0.0.12
+      uses: bitovi/github-actions-commons@v0.0.13
       with:
         # Current repo vars
         checkout: false
+        ansible_skip : false
         gh_action_repo: ${{ github.action_path }}
         gh_action_input_ansible: operations/deployment/ansible
-        ansible_skip : ${{ inputs.infrastructure_only }}
         env_ghs: ${{ inputs.env_ghs }}
 
         # AWS
@@ -220,8 +362,8 @@ runs:
 
         # Docker
         docker_install: true
-        docker_cloudwatch_enable: true
-        docker_cloudwatch_skip_destroy: true
+        docker_cloudwatch_enable: ${{ inputs.docker_cloudwatch_enable }}
+        docker_cloudwatch_skip_destroy: ${{ inputs.docker_cloudwatch_skip_destroy }}
         docker_repo_app_directory: pixel-tracker-app
 
         # EC2
@@ -229,19 +371,17 @@ runs:
         aws_ec2_ami_filter: ${{ inputs.aws_ec2_ami_filter }}
         aws_ec2_iam_instance_profile: ${{ inputs.aws_ec2_instance_profile }}
         aws_ec2_instance_type: ${{ inputs.aws_ec2_instance_type }}
-        aws_ec2_instance_public_ip: true
+        aws_ec2_instance_public_ip: ${{ inputs.aws_ec2_instance_public_ip }}
         aws_ec2_create_keypair_sm: ${{ inputs.aws_ec2_create_keypair_sm }}
         aws_ec2_instance_root_vol_size: ${{ inputs.aws_ec2_instance_vol_size }}
         aws_ec2_additional_tags: ${{ inputs.aws_ec2_additional_tags }}
-        aws_ec2_port_list:       "8000,3000"
+        aws_ec2_port_list: ${{ inputs.aws_ec2_port_list }}
         
         # AWS ELB
         aws_elb_create: true
-        aws_elb_listen_port:     "443,3000"
-        #aws_elb_listen_protocol: "SSL,TCP"
-        aws_elb_app_port:        "8000,3000"
-        #aws_elb_app_protocol:    "SSL,TCP"
-        aws_elb_healthcheck:     "HTTP:8000/"
+        aws_elb_listen_port: ${{ inputs.aws_elb_listen_port }}
+        aws_elb_app_port: ${{ inputs.aws_elb_app_port }}
+        aws_elb_healthcheck: "HTTP:8000/"
 
         # Stack management
         tf_stack_destroy: ${{ inputs.tf_stack_destroy }}
@@ -269,4 +409,7 @@ runs:
         aws_vpc_availability_zones: ${{ inputs.aws_vpc_availability_zones }}
         aws_vpc_id: ${{ inputs.aws_vpc_id }}
         aws_vpc_subnet_id: ${{ inputs.aws_vpc_subnet_id }}
+        aws_vpc_enable_nat_gateway: ${{ inputs.aws_vpc_enable_nat_gateway }}
+        aws_vpc_single_nat_gateway: ${{ inputs.aws_vpc_single_nat_gateway }}
+        aws_vpc_external_nat_ip_ids: ${{ inputs.aws_vpc_external_nat_ip_ids }}
         aws_vpc_additional_tags: ${{ inputs.aws_vpc_additional_tags }}
